FROM debian:bullseye-slim

RUN apt-get update && \
    apt-get -y install \
        binutils \
        rubygems \ 
        squashfs-tools \
        wget && \
    gem install fpm && \
    wget https://go.dev/dl/go1.19.linux-amd64.tar.gz && \
    tar -C /usr/local -xzf go1.19.linux-amd64.tar.gz

ENV PATH="${PATH}:/usr/local/go/bin"

WORKDIR /work
COPY . /work

RUN go mod tidy
VOLUME /work