// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package worker

import (
	"context"
	"discord-bot/pkg/shared/appconfig"
	"discord-bot/pkg/shared/clock"
	"discord-bot/pkg/shared/httpclient"
	"discord-bot/pkg/shared/logging"
	"discord-bot/pkg/worker/workerconfig"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitService(ctx context.Context) (*Service, error) {
	awsConfigManagerImpl := appconfig.NewAwsConfigManager()
	config, err := workerconfig.NewConfig(ctx, awsConfigManagerImpl)
	if err != nil {
		return nil, err
	}
	realTimeSource := clock.NewRealTimeSource()
	common := config.Common
	loggingConfig := common.Logging
	logger := logging.DefaultLogger(ctx, loggingConfig)
	client := httpclient.DefaultClient(realTimeSource, logger)
	sgfMeetupApiEventService := NewMeetupEventService(config, client, logger)
	httpDiscordNotifierService := NewDiscordNotifierService(config, client, logger)
	service := NewService(sgfMeetupApiEventService, httpDiscordNotifierService, realTimeSource, logger)
	return service, nil
}

// wire.go:

var CommonProviders = wire.NewSet(workerconfig.ConfigProviders, clock.RealClockProvider, logging.DefaultLogger, httpclient.DefaultClient)
